[package]
name = "timein"
description = "This is a simple utility for finding relative times"
version = "0.1.0"
edition = "2024"
readme = true
repository = "https://github.com/23Marbles/time-in"
license = "MIT OR Apache-2.0"
keywords = ["time", "cli", "utility"]
categories = ["command-line-utilities", "date-and-time"]

[[bin]]
name = "time"

[features]
show_weeks = []

[dependencies]
chrono = "0.4.45"
chrono-tz = "0.10.4"
clap = { version = "4.6.6", features = ["derive"] }
color-eyre = "0.6.5"
num-integer = "0.1.47"
num-traits = "0.2.19"
thiserror = "2.0.20"
